export default [
    'Acme',
    'Aladin',
    'Alegreya',
    'Amatic SC',
    'Amethysta',
    'Amiri',
    'Amita',
    'Aref Ruqaa',
    'Bad Script',
    'Calligraffitti',
    'Cardo',
    'Cinzel',
    'Cinzel Decorative',
    'Cormorant Infant',
    'Crimson Text',
    'EB Garamond',
    'El Messiri',
    'Fondamento',
    'Forum',
    'Gabriela',
    'Gilda Display',
    'Gloria Hallelujah',
    'Kalam',
    'Kaushan Script',
    'Kurale',
    'Lobster Two',
    'Lobster',
    'Love Ya Like A Sister',
    'Merienda',
    'Merienda One',
    'Nothing You Could Do',
    'Permanent Marker',
    'Satisfy',
    'Signika',
    'Tangerine'
];