export default [
    'Acme',
    'Aladin',
    'Alegreya',
    'Amatic SC',
    'Amethysta',
    'Amiri',
    'Amita',
    'Aref Ruqaa',
    'Bad Script',
    'Buffalo Western',
    'Calligraffitti',
    'Cardo',
    'Cinzel Decorative',
    'Cinzel',
    'Cormorant Infant',
    'Country Western',
    'Cowboy Western',
    'Crimson Text',
    'EB Garamond',
    'El Messiri',
    'Fondamento',
    'Forum',
    'Gabriela',
    'Gilda Display',
    'Gloria Hallelujah',
    'Kalam',
    'Kaushan Script',
    'Kurale',
    'Lobster Two',
    'Lobster',
    'Love Ya Like A Sister',
    'Merienda One',
    'Merienda',
    'Nothing You Could Do',
    'Permanent Marker',
    'Satisfy',
    'Signika',
    'Spaghetti Western NF',
    'Tangerine',
    'West Wind',
    'Xenia Western'
];